### PR TITLE
fix: Added recommended option

### LINKED ISSUE #336: '(Recommended)' text is missing on Define landscape boundary  screen
## Description
the ui text includes ' (Recommended)'  for the adding a Geojson file.

## Steps To Reproduce
1. Go to URL: 'https://app.terraso.org/landscapes/new'
2. Fill the Landscape profile form and click 'Next'
3. See the 3 options for the landscape boundary 

## Expected behavior
[design mockup]
image

## Actual behavior

image

### PR DESCRIPTION
**Pull request by josebui**
## Description

- Added recommended option

### Checklist
- [x] Corresponding issue has been opened
- [x] New tests added
- [ ] English strings reviewed and copyedited
- [x] Strings are localized
- [x] Verified on mobile
- [x] Verified on desktop
- [x] Verified accessibility ([Accessibility - Web applications](https://docs.google.com/document/d/1VwPDyLqw7r_iISMgDZr1FdAmAqqOIIVIxQqsYA-HaHE/edit?usp=sharing))

### Related Issues
Fixes #336 

### Verification steps

Screen Shot 2022-06-13 at 5 43 00 PM

### CODE REVIEW

**Comment by paulschreiber** [comment]
Not approved until this is styled.

**Review by cacarrara — APPROVED** [review]

**Comment by josebui** [comment]
@paulschreiber can you add more context on what are you expecting when you say: `Not approved until this is styled.`?

**Comment by paulschreiber** [comment]
@josebui We need an improved design (color, size, placement) before this is good enough to deploy.

**Comment by josebui** [comment]
@paulschreiber So this needs to be fixed by @Hanal-code ?

**Pull request closed without merging**
