### PR TITLE
fix: use distinct text when leaving landscapes and groups

### LINKED ISSUE #160: Leave landscape confirmation dialog uses same text about leaving groups
## Description
When you leave a landscape, the confirmation dialog uses the same text used to leave a group.

### PR DESCRIPTION
**Pull request by paulschreiber**
## Description
Pass in custom text and title to the confirmation dialog for leaving groups and landscapes.

### Checklist
- [X] Corresponding issue has been opened
- [x] New tests added
- [X] Strings are localized
- [X] Verified on mobile
- [X] Verified on desktop

### Related Issues
Fixes #160.

### Verification steps
1. Go to a group, i.e. http://127.0.0.1:3000/groups/acus-penninsula-galera-san-francisco
2. Click leave
3. Confirm group-specific language
4. Go to a landscape, i.e. http://127.0.0.1:3000/landscapes/acus-penninsula-galera-san-francisco
5. Click leave
6. Confirm landscape-specific language

### CODE REVIEW

**Comment by paulschreiber** [comment]
@josebui I would like to add tests to ensure the text is correct. Can you help with this?

**Comment by josebui** [comment]
@paulschreiber it seems you changed the tests, do you still need help?

**Comment by paulschreiber** [comment]
@josebui I fixed the existing tests, but want to add new ones to ensure the language in the confirmation dialog is correct.

**Comment by josebui** [comment]
@paulschreiber Paul I added some tests asserts and renamed some properties, let me know if that is enough

**Pull request merged**
